## roles/bind/tasks/main.yml
## Role main file
# vim:ft=ansible
---
# Initialise distribution-specific variables
- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: httpd

- name: Check whether `bind_zone_master_server_ip` was set
  assert:
    that: bind_zone_master_server_ip is defined

- name: Install BIND
  package:
    pkg: "{{ item }}"
    state: installed
  with_items: "{{ bind_packages }}"
  tags: bind

- name: Ensure runtime directories referenced in config exist
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: "{{ bind_group }}"
    mode: 0770
  with_items:
    - "{{ bind_dir }}/dynamic"
    - "{{ bind_dir }}/data"
  tags: bind

- name: Create serial, based on last two digits of year, month, day, and hour
  command: date +%y%m%d%H%M
  register: timestamp
  changed_when: false
  tags: bind

- include_tasks: master.yml
  when: bind_zone_master_server_ip in ansible_all_ipv4_addresses

- include_tasks: slave.yml
  when: bind_zone_master_server_ip not in ansible_all_ipv4_addresses

- name: Start BIND service
  service:
    name: "{{ bind_service }}"
    state: started
    enabled: yes
  tags: bind

- name: Add firewall exceptions
  firewalld:
    service: dns
    permanent: true
    state: enabled
    immediate: true
  when: "'RedHat' in ansible_os_family"

...
